/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bt.UI;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Kirbey García
 */
public class BluetoothUI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public BluetoothUI() {
        initComponents();
        JFreeChart Grafica;
        
        final XYSeries serie = new XYSeries("Temperatura");
        final XYSeriesCollection collection = new XYSeriesCollection();
        
        this.setVisible(true);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setTitle("Counter of temperature by bluetooth");
        
        serie.add(0, 0);
        collection.addSeries(serie);
        Grafica = ChartFactory.createXYLineChart("Temperatura por segundo", "Segundo", "Temperatura",
        collection, PlotOrientation.VERTICAL, true, true, false);
        
        int minutos = 0;
        int segundo = 0 ;
        int temperatura = 5;

            //Ventana de la 
            graficPanel = new ChartPanel(Grafica);
            JFrame representarGrafica = new JFrame();
            representarGrafica.getContentPane().add(graficPanel);
            representarGrafica.pack();
            representarGrafica.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            representarGrafica.setLocationRelativeTo(null);
            representarGrafica.setVisible(true);
            representarGrafica.setSize(800, 600);
        while (segundo>=0){
            temperatura++;
            segundo++;
            if(segundo == 60){
                segundo = 0;
                minutos++;
            }
            
            JLabel timeLabel = new JLabel();
            JLabel temperatureLabel = new JLabel();
            timeLabel.setText("Segundo " +segundo);
            temperatureLabel.setText("Temperatura " +temperatura);
            
            JPanel otroPanel = new JPanel();
            otroPanel.setLocation(0, 0);
            this.add(otroPanel);
            otroPanel.add(timeLabel);
            otroPanel.add(temperatureLabel);
            System.out.println(minutos+":"+segundo);
            serie.add(segundo, temperatura);
            delaySegundo(); 
            }
        }
    
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graficPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graficPanelLayout = new javax.swing.GroupLayout(graficPanel);
        graficPanel.setLayout(graficPanelLayout);
        graficPanelLayout.setHorizontalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        graficPanelLayout.setVerticalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graficPanel;
    // End of variables declaration//GEN-END:variables
    private static void delaySegundo(){      
             try{Thread.sleep(1000);
             }catch(InterruptedException e){
             }
        }

}
