/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bt.UI;
import java.awt.*;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.*;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Kirbey García
 */
public class BluetoothUI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public BluetoothUI() {
        initComponents();
        JFreeChart Grafica;
        
        this.setVisible(true);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setTitle("Counter of temperature by bluetooth");
        
        Grafica = ChartFactory.createLineChart3D("Temperatura por segundo", "Segundo", "Temperatura",
        Datos, PlotOrientation.VERTICAL, true, true, false);
        
        Datos.addValue(26, "Temperatura", "1s");
        Datos.addValue(27, "Temperatura", "2s");
        Datos.addValue(27, "Temperatura", "3s");
        Datos.addValue(28, "Temperatura", "4s");
        Datos.addValue(29, "Temperatura", "5s");
        Datos.addValue(25, "Temperatura", "6s");
        Datos.addValue(26, "Temperatura", "7s");
        graficPanel = new ChartPanel(Grafica);
        
        //Ventana de la 
        JFrame representarGrafica = new JFrame();
        representarGrafica.getContentPane().add(graficPanel);
        representarGrafica.pack();
        representarGrafica.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        representarGrafica.setLocationRelativeTo(null);
        representarGrafica.setVisible(true);
        representarGrafica.setSize(800, 600);
        }
    
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graficPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graficPanelLayout = new javax.swing.GroupLayout(graficPanel);
        graficPanel.setLayout(graficPanelLayout);
        graficPanelLayout.setHorizontalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        graficPanelLayout.setVerticalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graficPanel;
    // End of variables declaration//GEN-END:variables
}
