/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bt.UI;
/**
 *
 * @author Kirbey García
 */
public class BluetoothUI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public BluetoothUI() {
<<<<<<< HEAD
        
    }
=======
        initComponents();
        JFreeChart Grafica;
        
        final XYSeries serie = new XYSeries("Temperatura");
        final XYSeriesCollection collection = new XYSeriesCollection();
        
        this.setVisible(true);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setTitle("Counter of temperature by bluetooth");
        
        serie.add(0, 0);
        collection.addSeries(serie);
        Grafica = ChartFactory.createXYLineChart("Temperature every second", "Second", "Temperature",
        collection, PlotOrientation.VERTICAL, true, true, false);
        
        int segundo = 0 ;
        int temperatura = 0;
        float average = 0;
        float temperaturas = 0;

            //Ventana de la 
            graficPanel = new ChartPanel(Grafica);
            JFrame representarGrafica = new JFrame();
            representarGrafica.getContentPane().add(graficPanel);
            representarGrafica.pack();
            representarGrafica.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            representarGrafica.setLocationRelativeTo(null);
            representarGrafica.setVisible(true);
            representarGrafica.setSize(800, 600);
        while (segundo>=0){
            temperatura=temperatura^(temperatura++-segundo);
            segundo++;
            temperaturas = temperaturas+temperatura;
            average = temperaturas/segundo;
            
            timeLabel.setText("Segundo " +segundo);
            temperatureLabel.setText("Temperatura " +temperatura +"ºC");
            averageLabel.setText("Promedio " +average +"ºC");
            System.out.println("Tiempo actual: "+segundo);
            serie.add(segundo, temperatura);
            delaySegundo(); 
            }
        }
>>>>>>> cd872def83563acde12fdf87a8efbc628b10d5a8
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graficPanel = new javax.swing.JPanel();
<<<<<<< HEAD
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelito = new javax.swing.JPanel();
=======
        timeLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        averageLabel = new javax.swing.JLabel();
>>>>>>> cd872def83563acde12fdf87a8efbc628b10d5a8

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        graficPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        graficPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelitoLayout = new javax.swing.GroupLayout(panelito);
        panelito.setLayout(panelitoLayout);
        panelitoLayout.setHorizontalGroup(
            panelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        panelitoLayout.setVerticalGroup(
            panelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graficPanelLayout = new javax.swing.GroupLayout(graficPanel);
        graficPanel.setLayout(graficPanelLayout);
        graficPanelLayout.setHorizontalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        graficPanelLayout.setVerticalGroup(
            graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
            .addGroup(graficPanelLayout.createSequentialGroup()
                .addGroup(graficPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graficPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(graficPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
=======
            .addGap(0, 250, Short.MAX_VALUE)
>>>>>>> cd872def83563acde12fdf87a8efbc628b10d5a8
        );

        timeLabel.setText("timeLabel");

        temperatureLabel.setText("temperatureLabel");

        averageLabel.setText("averageLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graficPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(averageLabel)
                .addGap(95, 95, 95)
                .addComponent(temperatureLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(temperatureLabel)
                    .addComponent(averageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(graficPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageLabel;
    private javax.swing.JPanel graficPanel;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelito;
=======
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel timeLabel;
>>>>>>> cd872def83563acde12fdf87a8efbc628b10d5a8
    // End of variables declaration//GEN-END:variables
}
